[tool.poetry]
name = "views-stepshifter"
version = "0.1.0"
description = ""
authors = ["Xiaolong Sun <xiaolong.sun@pcr.uu.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
views_pipeline_core = "^0.1.0"
scikit-learn = "^1.2.2"
pandas = "^1.5.3"
numpy = "^1.25.2"
darts = "^0.30.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
